// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacramentMeetingPlanner.Models;
using System;

namespace SacramentMeetingPlanner.Migrations
{
    [DbContext(typeof(SacramentMeetingPlannerContext))]
    [Migration("20180404041758_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentMeetingPlanner.Models.Sacrament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Conducting")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("HymnName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("HymnNumber")
                        .HasColumnName("HymnNumber");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<string>("Prayers")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Speakers")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Sacrament");
                });
#pragma warning restore 612, 618
        }
    }
}
